/* cmockaTest.h CONTAINS A FUNCTION DESCRIBED IN cmockaTest.c THAT IS USED
IN main.c TO CONDUCT UNIT TESTS OF chat.h MODULE */

#ifndef CMOCKATEST_H_INCLUDED
#define CMOCKATEST_H_INCLUDED

void cmockaTest(void);

#endif // CMOCKATEST_H_INCLUDED