# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id_album', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('format', models.CharField(blank=True, max_length=6, null=True)),
                ('number_of_tracks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id_artist', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_members', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongReleases',
            fields=[
                ('id_song_release', models.AutoField(primary_key=True, serialize=False)),
                ('date_release', models.DateField()),
            ],
            options={
                'db_table': 'song_releases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id_song', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('number_in_album', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'songs',
                'managed': False,
            },
        ),
    ]
